experiment_name: biocs_plus_kd_only_lkd2_c100

dataset:
  data_root: ./dataset
  n_tasks: 10
  name: split_cifar100

model:
  name: resnet18

method:
  name: biocs_plus
  biocs_targets: [classifier]
  lambda_spatial: 0.0
  lambda_distill: 2.0
  lambda_feat: 0.0
  lambda_replay: 0.0
  lambda_spectral: 0.0
  temperature: 3.0

training:
  epochs: 50
  batch_size: 512
  optimizer: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0
  scheduler: multistep
  milestones: [35, 45]
  gamma: 0.1
  grad_clip: 5.0
  use_amp: true
  num_workers: 4
