dataset:
  data_root: ./dataset
  n_tasks: 5
  name: split_cifar10
experiment_name: ewc_split_cifar10
method:
  ewc_lambda: 400
  name: ewc
model:
  name: resnet18
training:
  batch_size: 128
  epochs: 50
  gamma: 0.1
  grad_clip: 5.0
  lr: 0.1
  milestones:
  - 35
  - 45
  momentum: 0.9
  num_workers: 4
  optimizer: sgd
  scheduler: multistep
  use_amp: true
  weight_decay: 0.0
